package com.sample
 
import com.sample.Message;
import com.drools.rules.model.ApplicationDTO

rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end


rule "Dead person"
    when
     application : ApplicationDTO(age >= 100)
    then
    application.setResponse("Age is Above 100 ! You should be dead by now ! ");
end
